### ISSUE TITLE
gh-pages: https://ISKME.github.io/Open-Metadata-Exchange/ does not work

### ISSUE THREAD

**Issue by cclauss** [ISKME/Open-Metadata-Exchange#8]
https://ISKME.github.io/Open-Metadata-Exchange/ does not work.

[.github/workflows/sphinx.yml](https://github.com/ISKME/Open-Metadata-Exchange/blob/main/.github/workflows/sphinx.yml) appears to be generating a proper [`gh-pages` branch](https://github.com/ISKME/Open-Metadata-Exchange/tree/gh-pages) but the https://ISKME.github.io/Open-Metadata-Exchange/ returns a 404. 😞

@chrisjsewell If you have any insight on our GitHub Action or our `gh-pages` branch, that would be warmly received.

**Comment by chrisjsewell** [comment]
Heya, So generally I always use [readthedocs](https://readthedocs.org) for deployment,
but actually for a recent private project I've had to use gh-pages (without any third-party actions) and this works for me.

It uses rye to manage the build environment, but you should get the idea.

I adapted it from the template actions no github for things like nextjs

```
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Install the latest version of rye
        run: |
          curl -sSf https://rye.astral.sh/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: "latest"
          RYE_INSTALL_OPTION: "--yes"
      - run: rye sync
      - name: Run documentation build
        run: rye run docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
